import React from 'react'

export default function About() {
  return (
    <div style={{margin: "30px", minHeight: "75.5vh"}}>
        <h1>This is About Component of Todos List</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus voluptatum incidunt veniam, minus voluptatibus consequuntur obcaecati optio. Explicabo, sed et numquam quas consectetur ipsam amet, ea nihil distinctio deserunt animi molestiae provident odio ducimus maxime modi eius dolor consequuntur non totam illum error dolores rerum. Perferendis sint inventore aliquid itaque. Aspernatur veniam aut quis aperiam fuga ab nam dolore enim corrupti distinctio consequatur repellendus ipsa facilis hic, vitae fugit dolorum! Nulla, maiores. Perspiciatis iusto dolorum corrupti distinctio doloremque quasi rem delectus id, in tenetur totam. Adipisci sapiente eos at nemo atque quisquam quo, aperiam voluptatem reprehenderit. Explicabo id consequatur iure vel pariatur facilis aliquam officia voluptatum! Eaque nihil ratione placeat similique iusto nobis corrupti doloremque perferendis voluptate aliquid ea voluptatem, distinctio, ex rem porro minus dolore? Illum dicta dolor quisquam in tenetur placeat dignissimos ea nihil harum ipsum, dolore, quod quibusdam explicabo perspiciatis, minima praesentium voluptatum. Ipsum, pariatur blanditiis! Dolores sed, nisi voluptate assumenda soluta ex, nobis numquam cumque doloribus beatae, suscipit quaerat ut vero temporibus sequi non aspernatur quo tenetur explicabo qui deserunt? Sed nobis exercitationem laudantium tempora iusto officiis odio fugiat placeat cum, dolore facere eligendi tempore optio quisquam perferendis? Sapiente, nobis. Inventore est, voluptatum eos blanditiis illo itaque accusantium officiis, doloribus eligendi, consectetur dolores error nam consequatur perspiciatis facilis distinctio. Iusto, ex consequuntur, quos cupiditate deserunt neque et aut ratione nesciunt aperiam suscipit repudiandae. Veniam veritatis incidunt quam fugit eaque molestias suscipit fuga, nisi tempore consectetur consequuntur ipsa enim corporis ipsam cum neque ab unde vitae deserunt quae ullam iusto dolor excepturi exercitationem! Amet quam id dolor nihil doloremque iste numquam eligendi ut nobis iusto, minus ad necessitatibus ullam molestiae reiciendis obcaecati vel? Sunt voluptatum quaerat quasi dignissimos ad. Sequi alias qui iste illo velit iusto reprehenderit labore a dolorum ducimus? Voluptate soluta dignissimos aut veritatis nam.</p>
    </div>
  )
}
